# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sO3m--2KIuqeskxikJ55B3rH55SN-ze_
"""

# @title Task_1
#Assigning values to variable
a = 10
b = "Hello World!"
1c = True
class = 66.56
e-z = 10000

#print the variable
print(a, b, 1c, class, e-z)

# @title Task_2

#using input and output in python

a = float (input("Enter the first value: "))

b = float (input("Enter the Second value: "))

operator = input("Enter the operator to use: ")

if operator == "+":
    result = a + b

elif operator == "-":
    result = a - b

elif operator == "*":
    result = a * b

elif operator == "//":
    result = a // b

elif operator == "/":
   result = a / b

elif operator == "**":
   result = a ** b

else :
  print("Incorrect operator!")

#print the variable
print(result)

# @title Task_3

#using input and output in python

a = float (input("Enter the first value: "))

b = float (input("Enter the Second value: "))

c = float (input("Enter the Third value: "))


if a == b == c:
    print("all are equal")

elif a > b > c:
    print("a is greatest")
    print("Descending order!")

elif a < b > c:
    print("b is greatest")


elif a < b < c:
    print("c is greatest")
    print("Ascending order!")

else :
  print("Incorrect")

# @title Task_4

#using input

a = float (input("Enter the first value: "))

b = float (input("Enter the Second value: "))

#print the variable before swapping
print(a, b)

temp = a
a = b
b = temp


#print the variable after swapping
print(a, b)

# @title Task_5

#using input and output in python

x, y, z = 5, 10, 15


#print the variable
print(x, y, z)

x, y, z = 20, 25, 30


#print the updated variable
print(x, y, z)